import fs from 'fs'
import path from 'path'
import { glob } from 'glob'

export function readJSON<T = unknown>(filePath: string): T {
  const raw = fs.readFileSync(filePath, 'utf-8')
  return JSON.parse(raw) as T
}

export function writeFile(filePath: string, content: string): void {
  fs.mkdirSync(path.dirname(filePath), { recursive: true })
  fs.writeFileSync(filePath, content, 'utf-8')
}

export function fileExists(filePath: string): boolean {
  return fs.existsSync(filePath)
}

export function readFileIfExists(filePath: string): string | null {
  if (!fs.existsSync(filePath)) return null
  return fs.readFileSync(filePath, 'utf-8')
}

export async function globJSON<T = unknown>(pattern: string, cwd: string): Promise<Array<{ file: string; data: T }>> {
  const files = await glob(pattern, { cwd, absolute: true })
  return files.map(file => ({
    file,
    data: readJSON<T>(file),
  }))
}

export function stripGeneratedHeader(content: string): string {
  const lines = content.split('\n')
  // Skip lines up to and including the generated header block
  let i = 0
  while (i < lines.length && (lines[i].startsWith('//') || lines[i].startsWith('<!--') || lines[i].trim() === '')) {
    i++
  }
  return lines.slice(i).join('\n')
}

export function generatedHeader(tool: string, source: string): string {
  return [
    `// ─────────────────────────────────────────────────────────────────────────────`,
    `// GENERATED BY SENTINEL — DO NOT EDIT BY HAND`,
    `// Tool:   ${tool}`,
    `// Source: ${source}`,
    `// Run "sentinel schema:generate" to regenerate`,
    `// ─────────────────────────────────────────────────────────────────────────────`,
    ``,
  ].join('\n')
}

export function xmlGeneratedHeader(source: string): string {
  return [
    `<?xml version="1.0" encoding="utf-8"?>`,
    `<!-- GENERATED BY SENTINEL — DO NOT EDIT BY HAND -->`,
    `<!-- Source: ${source} -->`,
    `<!-- Run "sentinel schema:generate" to regenerate -->`,
    ``,
  ].join('\n')
}

// Convert dot-notation key to camelCase parts
// e.g. "workout.start_button" → ["workout", "startButton"]
export function parseStringKey(key: string): { namespace: string; name: string } {
  const parts = key.split('.')
  const namespace = parts[0]
  const name = parts
    .slice(1)
    .map((p, i) => i === 0 ? p : p.charAt(0).toUpperCase() + p.slice(1))
    .join('')
    .replace(/_([a-z])/g, (_, c: string) => c.toUpperCase())
  return { namespace, name }
}

// Convert snake_case or dot.case key to Android resource name (underscored)
// e.g. "workout.start_button" → "workout_start_button"
export function toAndroidKey(key: string): string {
  return key.replace(/\./g, '_').replace(/([A-Z])/g, '_$1').toLowerCase()
}

// Convert token path to Swift identifier
// e.g. "colors.brand.primary" → ["Colors", "Brand", "primary"]
export function tokenPathToSwift(path: string[]): string {
  return path.map((p, i) => i < path.length - 1
    ? p.charAt(0).toUpperCase() + p.slice(1)
    : p
  ).join('.')
}

// Convert px/ms string to number
export function parseDimension(value: string): number {
  return parseFloat(value.replace(/[^0-9.]/g, ''))
}

export function parseDimensionUnit(value: string): string {
  const match = value.match(/[a-z%]+$/)
  return match ? match[0] : ''
}
